name: Tests
on: [ pull_request ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]
        sf_version: [ '3.4.*', '4.4.*', '5.3.*' ]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: flex

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.sf_version }}
        uses: ramsey/composer-install@v1

      - name: Run tests
        run: ./vendor/bin/simple-phpunit

  lowest:
    name: Lowest deps
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.5.0
        with:
          php-version: 7.3
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        with:
          dependency-versions: "lowest"
        uses: ramsey/composer-install@v1

      - name: Run tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: "max[self]=0"
        run: ./vendor/bin/simple-phpunit
