name: Tests
on: [ pull_request ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        versions:
          - sf: '6.4.*'
            php: '8.1'
          - sf: '6.4.*'
            php: '8.2'
          - sf: '6.4.*'
            php: '8.3'
          - sf: '7.1.*'
            php: '8.2'
          - sf: '7.1.*'
            php: '8.3'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: ${{ matrix.versions.php }}
          coverage: none
          tools: flex

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.versions.sf }}
        uses: ramsey/composer-install@v1

      - name: Run tests
        run: ./vendor/bin/simple-phpunit

  lowest:
    name: Lowest deps
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.5.0
        with:
          php-version: 8.3
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        with:
          dependency-versions: "lowest"
        uses: ramsey/composer-install@v1

      - name: Run tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: "max[self]=0"
        run: ./vendor/bin/simple-phpunit
